using System;
using System.IO;
using System.Text;

namespace projectFrameCut.PluginPackager.MSBuild
{
    public static class PartialClassGenerator
    {
        public static string GeneratePartialClassFile(string PluginID, string PluginVersion, string PluginPublishUrl, string NeutralLanguageDisplayName, string Authors, string NeutralLanguageDescription, string PluginProjectUrl, string ProjectRootPath, bool GenerateInfo, bool isAppLevel = false, int pluginMajorVersion = PluginBuilder.CurrentPluginAPIVersion, int minorVersion = 0, int appLevelPluginMajorVersion = PluginBuilder.CurrentAppLevelPluginVersion, bool GenerateLoader = true, string generatedOutputDirectory = null)
        {
            if (string.IsNullOrWhiteSpace(PluginID)) throw new InvalidOperationException("PluginID is required to generate plugin source.");
            var idx = PluginID.LastIndexOf('.');
            string ns = idx > 0 ? PluginID.Substring(0, idx) : "nobody";
            string className = idx > 0 ? PluginID.Substring(idx + 1) : PluginID;

            Version v = null;
            if (!Version.TryParse(PluginVersion, out v))
            {
                v = new Version(1, 0, 0, 0);
            }
            int major = v.Major;
            int minor = v.Minor;
            int build = v.Build < 0 ? 0 : v.Build;
            int rev = v.Revision < 0 ? 0 : v.Revision;

            string Escape(string s) => s == null ? string.Empty : s.Replace("\\", "\\\\").Replace("\"", "\\\"");
            string ToCSharpStringLiteral(string value) => value == null ? "null" : "\"" + Escape(value) + "\"";

            var publishExpr = string.IsNullOrWhiteSpace(PluginPublishUrl) ? null : PluginPublishUrl;

            var writer = new StringBuilder();
            writer.AppendLine("// <auto-generated>");
            writer.AppendLine("// This code was generated by projectFrameCut.PluginPackager.MSBuild.");
            writer.AppendLine("// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
            writer.AppendLine();
            writer.AppendLine("#nullable enable");
            writer.AppendLine("#pragma warning disable IDE0130");
            writer.AppendLine("#pragma warning disable CS8603");
            writer.AppendLine();
            if (GenerateInfo)
            {
                writer.AppendLine($"namespace {ns}");
                writer.AppendLine("{");
                writer.AppendLine("    using System;");
                writer.AppendLine("    using System.CodeDom.Compiler;");
                writer.AppendLine("    using projectFrameCut.Render.RenderAPIBase.Plugins;");
                writer.AppendLine();
                writer.AppendLine("    [GeneratedCode(\"projectFrameCut.PluginPackager.MSBuild\", null)]");
                writer.AppendLine($"    public partial class {className}");
                writer.AppendLine("    {");
                writer.AppendLine($"        public string PluginID => {ToCSharpStringLiteral(PluginID)};");
                writer.AppendLine($"        public int PluginAPIVersion => {pluginMajorVersion};");
                writer.AppendLine($"        public int PluginAPIMinorVersion => {minorVersion};");
                writer.AppendLine($"        public string Name => {ToCSharpStringLiteral(NeutralLanguageDisplayName)};");
                writer.AppendLine($"        public string Author => {ToCSharpStringLiteral(Authors)};");
                writer.AppendLine($"        public string Description => {ToCSharpStringLiteral(NeutralLanguageDescription)};");
                writer.AppendLine($"        public Version Version => new Version({major}, {minor}, {build}, {rev});");
                writer.AppendLine($"        public string AuthorUrl => {ToCSharpStringLiteral(PluginProjectUrl)};");
                writer.AppendLine($"        public string PublishingUrl => {ToCSharpStringLiteral(publishExpr)};");
                if (isAppLevel)
                {
                    writer.AppendLine($"                public int AppLevelPluginAPIVersion => {appLevelPluginMajorVersion};");
                }
                writer.AppendLine("    }");
                writer.AppendLine("}");
            }
            if (GenerateLoader)
            {
                var loaderName = (isAppLevel ? "AppLevel" : string.Empty) + "PluginLoader";
                writer.AppendLine();
                writer.AppendLine("namespace projectFrameCut.Plugin");
                writer.AppendLine("{");
                writer.AppendLine("    using System;");
                writer.AppendLine("    using System.CodeDom.Compiler;");
                writer.AppendLine("    using projectFrameCut.Render.RenderAPIBase.Plugins;");
                writer.AppendLine();
                writer.AppendLine("    [GeneratedCode(\"projectFrameCut.PluginPackager.MSBuild\", null)]");
                writer.AppendLine($"    public partial class {loaderName}");
                writer.AppendLine("    {");
                writer.AppendLine($"        public static int PluginAPIVersion => {pluginMajorVersion};");
                writer.AppendLine("        public static string LocaleId = \"en-US\";");
                writer.AppendLine("        public static string PluginRoot = string.Empty;");
                writer.AppendLine();
                writer.AppendLine("        public static IPluginBase CreateInstance(string currentLocale, string pluginRoot)");
                writer.AppendLine("        {");
                writer.AppendLine("            LocaleId = currentLocale;");
                writer.AppendLine("            PluginRoot = pluginRoot;");
                writer.AppendLine($"            var instance = new {ns}.{className}();");
                writer.AppendLine("            projectFrameCut.Shared.Logger.LogDiagnostic(string.Format(\"PluginLoader for plugin '{0}' invoked.\", instance.Name));");
                writer.AppendLine("            return (IPluginBase)instance;");
                writer.AppendLine("        }");
                writer.AppendLine("    }");
                writer.AppendLine("}");
            }

            string baseDir;
            

            if (!string.IsNullOrWhiteSpace(generatedOutputDirectory))
            {
                baseDir = generatedOutputDirectory;
                if (!Path.IsPathRooted(baseDir))
                {
                    baseDir = Path.Combine(ProjectRootPath ?? Directory.GetCurrentDirectory(), baseDir);
                }
            }
            else if (!string.IsNullOrWhiteSpace(ProjectRootPath))
            {
                baseDir = Path.Combine(ProjectRootPath, "obj", "GeneratedSource");
            }
            else
            {
                baseDir = Path.Combine(Directory.GetCurrentDirectory(), "obj", "GeneratedSource");
            }

            Directory.CreateDirectory(baseDir);
            var outPath = Path.Combine(baseDir, "PluginInfo.sg.cs");
            File.WriteAllText(outPath, writer.ToString(), Encoding.UTF8);
            return outPath;
        }
    }
}

